providers:

    - name: ovh
      asns:
        - AS16276
    - name: google
      asns:
        - AS396982
        - AS16550
    - name: tencent
      asns:
        - AS45090
        - AS132203
    - name: Hetzner
      asns:
        - AS24940
    - name: microsoft
      asns:
        - AS8075
    - name: digitalocean
      asns:
        - AS14061
    - name: censys
      asns:
        - AS398324
    - name: akamai (linode)
      asns:
        - AS63949
    - name: ucloud.cn
      asns:
        - AS135377
    - name: alibaba
      asns:
        - AS45102
    - name: Amarutu
      asns:
        - AS206264
    - name: Datacamp
      asns:
        - AS212238
        - AS60068
    - name: Proton
      asns:
        - AS209103
    - name: MivoCloud
      asns:
        - AS39798
    - name: Host Universal
      asns:
        - AS136557
    - name: Farice
      asns:
        - AS56704
    - name: WorldStream
      asns:
        - AS49981
    - name: Bahnhof AB (never heard of it, lmao)
      asns:
        - AS8473
    - name: EstNOC
      asns:
        - AS206804
    - name: M247
      asns:
        - AS9009
    - name: owl.net
      asns:
        - AS23959
    - name: xTom
      asns:
        - AS4785
    - name: nforce.com
      asns:
        - AS43350
    - name: Performive LLC
      asns:
        - AS46562
    - name: THG HOSTING
      asns:
        - AS13213
    - name: GorillaServers
      asns:
        - AS53850
    - name: Oy Crea Nova
      asns:
        - AS51765
    - name: Orion Network
      asns:
        - AS41564
        - AS58065
    - name: GSL Networks
      asns:
        - AS137409
    - name: HostRoyale
      asns:
        - AS203020
    - name: Cloud Lease
      asns:
        - AS206446
    - name: Gcore
      asns:
        - AS199524
    - name: Interserver
      asns:
        - AS19318
    - name: NAVEGALO
      asns:
        - AS28110
    - name: AltusHost
      asns:
        - AS51430
    - name: UAB Bacloud
      asns:
        - AS61272
    - name: Convergence Group
      asns:
        - AS16247
    - name: Latitude.sh
      asns:
        - AS396356
        - AS262287
    - name: Intergrid AU
      asns:
        - AS133480
    - name: FDCservers.net
      asns:
        - AS30058
    - name: HostingInside
      asns:
        - AS9678
    - name: Cablenet CY
      asns:
        - AS35432
    - name: Fiber Grid
      asns:
        - AS37518
    - name: plus.hr
      asns:
        - AS12417
    - name: ukserver.com
      asns:
        - AS42831
    - name: GRUPO ZGH SPA
      asns:
        - AS263702
    - name: Global Layer
      asns:
        - AS49453
    - name: Gigabit Hosting
      asns:
        - AS55720
    - name: PacketHub
      asns:
        - AS141039
    - name: nexeon.com
      asns:
        - AS20278
